// GENERATED by tools/assets/gallery-photos.mjs. Do not edit by hand.
//
// Re-run it against the source folder to regenerate:
//   node tools/assets/gallery-photos.mjs <source-dir>
//
// PREVIOUS CAMP MEETINGS ONLY. This file is rewritten from top to bottom
// on every run, so anything typed into it is gone the next time the
// previous-years set is regenerated. Photographs from CAMP MEETING 2026
// go in src/data/gallery-2026.ts, which is hand-edited and which the
// generator does not open. The two are joined into the year collections
// the page renders by src/features/gallery/lib/collections.ts.
//
// The width and height are the file's real dimensions and are what the
// grid reserves space with, so nothing reflows as the images decode.
import type { GalleryImage } from "./types";

export const previousGalleryImages: GalleryImage[] = [
  { id: "camp-01", src: "/gallery/camp-01.webp", width: 1600, height: 1068 },
  { id: "camp-02", src: "/gallery/camp-02.webp", width: 1600, height: 1066 },
  { id: "camp-03", src: "/gallery/camp-03.webp", width: 1440, height: 960 },
  { id: "camp-04", src: "/gallery/camp-04.webp", width: 672, height: 1200 },
  { id: "camp-05", src: "/gallery/camp-05.webp", width: 1600, height: 896 },
  { id: "camp-06", src: "/gallery/camp-06.webp", width: 1600, height: 898 },
  { id: "camp-07", src: "/gallery/camp-07.webp", width: 1600, height: 898 },
  { id: "camp-08", src: "/gallery/camp-08.webp", width: 1600, height: 898 },
  { id: "camp-09", src: "/gallery/camp-09.webp", width: 1600, height: 898 },
  { id: "camp-10", src: "/gallery/camp-10.webp", width: 1600, height: 898 },
  { id: "camp-11", src: "/gallery/camp-11.webp", width: 1600, height: 747 },
  { id: "camp-12", src: "/gallery/camp-12.webp", width: 1600, height: 898 },
  { id: "camp-13", src: "/gallery/camp-13.webp", width: 1600, height: 898 },
  { id: "camp-14", src: "/gallery/camp-14.webp", width: 1600, height: 898 },
  { id: "camp-15", src: "/gallery/camp-15.webp", width: 1600, height: 1066 },
  { id: "camp-16", src: "/gallery/camp-16.webp", width: 1600, height: 1066 },
  { id: "camp-17", src: "/gallery/camp-17.webp", width: 1600, height: 1066 },
  { id: "camp-18", src: "/gallery/camp-18.webp", width: 846, height: 396 },
  { id: "camp-19", src: "/gallery/camp-19.webp", width: 960, height: 720 },
  { id: "camp-20", src: "/gallery/camp-20.webp", width: 1600, height: 1066 },
  { id: "camp-21", src: "/gallery/camp-21.webp", width: 1600, height: 1066 },
  { id: "camp-22", src: "/gallery/camp-22.webp", width: 960, height: 720 },
  { id: "camp-23", src: "/gallery/camp-23.webp", width: 960, height: 720 },
  { id: "camp-24", src: "/gallery/camp-24.webp", width: 960, height: 720 },
  { id: "camp-25", src: "/gallery/camp-25.webp", width: 960, height: 720 },
  { id: "camp-26", src: "/gallery/camp-26.webp", width: 960, height: 720 },
  { id: "camp-27", src: "/gallery/camp-27.webp", width: 1600, height: 1066 },
  { id: "camp-28", src: "/gallery/camp-28.webp", width: 1600, height: 1066 },
  { id: "camp-29", src: "/gallery/camp-29.webp", width: 1600, height: 1066 },
  { id: "camp-30", src: "/gallery/camp-30.webp", width: 1066, height: 1600 },
  { id: "camp-31", src: "/gallery/camp-31.webp", width: 1600, height: 1066 },
];
